# Generated by Django 4.0.3 on 2022-05-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handles', '0001_initial'),
        ('kindles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_kindle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kindles.directkindle')),
                ('handle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handles.handle')),
                ('seeking_kindle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kindles.seekingkindle')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, max_length=512)),
                ('unread', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_actor', to='notifications.actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_recipient', to='notifications.actor')),
            ],
        ),
    ]
