# Generated by Django 4.0.3 on 2022-03-27 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_period', models.DateField(blank=True, null=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('region', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America'), ('WW', 'Worldwide')], default='WW', max_length=2)),
                ('game_and_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameandplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='handle',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'game_and_platform'), name='unique-handle'),
        ),
    ]
