# Generated by Django 4.0.3 on 2022-05-02 23:41

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='cover.jpg', upload_to=games.models.rename_and_set_upload_path),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(default='icon.jpg', upload_to=games.models.rename_and_set_upload_path),
        ),
    ]
