# Generated by Django 4.0.3 on 2022-05-27 14:54

from django.db import migrations, models
import functools
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='cover.jpg', upload_to=functools.partial(games.models._get_upload_to_path, *(), **{'name': 'cover'})),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(default='icon.jpg', upload_to=functools.partial(games.models._get_upload_to_path, *(), **{'name': 'icon'})),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to=functools.partial(games.models._get_upload_to_path, *(), **{'name': 'image'})),
        ),
    ]
