# Generated by Django 4.0.3 on 2022-06-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_cover_alter_game_icon_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='abbreviation',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
