name: "rekindled CI"

on: [push, pull_request]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/virtualenvs

      - name: Install dependencies
        run: |
          poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Migrate database
        env:
          SECRET_KEY: "test"
          DEBUG: True
          CORS_WHITELIST: "*"
          CSRF_WHITELIST: "*"
          CORS_ORIGIN_WHITELIST: "http://localhost:3000"
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        env:
          SECRET_KEY: "test"
          DEBUG: True
          CORS_WHITELIST: "*"
          CSRF_WHITELIST: "*"
          CORS_ORIGIN_WHITELIST: "http://localhost:3000"
        run: |
          poetry run python manage.py test
